# Generated by Django 5.1.7 on 2025-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_virtue_studentprofile_phone_number_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=244)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
